// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_cp0faIcmIad1Upg3Watei6N0KnqOljk',
    appId: '1:970819321982:web:8c3b9ec698f49a0931582f',
    messagingSenderId: '970819321982',
    projectId: 'my-schedule-2d32b',
    authDomain: 'my-schedule-2d32b.firebaseapp.com',
    storageBucket: 'my-schedule-2d32b.appspot.com',
    measurementId: 'G-5Q4SQVHC1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo21L_jmYwOnCxk4chNnK46Ud__B8GDb4',
    appId: '1:970819321982:android:3b8338135158ccba31582f',
    messagingSenderId: '970819321982',
    projectId: 'my-schedule-2d32b',
    storageBucket: 'my-schedule-2d32b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd-4FRARZjAKlICWTDcF1v3z91O2y97co',
    appId: '1:970819321982:ios:40958f4adca1ae5631582f',
    messagingSenderId: '970819321982',
    projectId: 'my-schedule-2d32b',
    storageBucket: 'my-schedule-2d32b.appspot.com',
    iosClientId: '970819321982-u293hraq0pso7i9ln4i55peg8g5mng97.apps.googleusercontent.com',
    iosBundleId: 'com.equitysoft.mySchedule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd-4FRARZjAKlICWTDcF1v3z91O2y97co',
    appId: '1:970819321982:ios:40958f4adca1ae5631582f',
    messagingSenderId: '970819321982',
    projectId: 'my-schedule-2d32b',
    storageBucket: 'my-schedule-2d32b.appspot.com',
    iosClientId: '970819321982-u293hraq0pso7i9ln4i55peg8g5mng97.apps.googleusercontent.com',
    iosBundleId: 'com.equitysoft.mySchedule',
  );
}
